use std::collections::HashMap;
use serde::{Deserialize, Serialize};
use lazy_static::lazy_static;

use crate::types::GpsError;



#[derive(Debug, Serialize, Deserialize)]
pub struct CurrencyInfo{
    pub decimals: u32,
    pub iso_alpha_code: String,
    pub iso_numeric_code: String,
    pub name: &'static str,
    pub symbol: &'static str,
    pub symbol_first: bool,
    pub minor_denomination: u32,
}

lazy_static! {
    static ref ALPHA_CODE_TO_ENUM: HashMap<String, Currency> =
        gen_alpha_code_to_enum();

    static ref NUM_CODE_TO_ENUM: HashMap<String, Currency> =
        gen_num_code_to_enum();
}


/// Returns an enum value given an alphabetic ISO-4217 currency code.
pub fn find_by_alpha_code(code: &str) -> Result<Currency, GpsError> {
    match ALPHA_CODE_TO_ENUM.get(&code.to_uppercase()) {
        Some(c) => Ok(*c),
        None => Err(GpsError::CurrencyError(format!("The string '{}' is not a valid ISO alpha code for a currency", code))),
    }
}

/// Returns an enum value given a numeric ISO-4217 currency code.
pub fn find_by_numeric_code(code: &str) -> Result<Currency, GpsError> {
    match NUM_CODE_TO_ENUM.get(code) {
        Some(c) => Ok(*c),
        None => Err(GpsError::CurrencyError(format!("The string '{}' is not a valid ISO numeric code for a currency", code))),
    }
}

fn gen_alpha_code_to_enum() -> HashMap<String, Currency> {
    let mut num_map: HashMap<String, Currency> = HashMap::new();
    for item in ISO_CURRENCIES {
        let currency = get_currency_info(*item);
        num_map.insert(currency.iso_alpha_code.to_string(), *item);
    }
    num_map
}

fn gen_num_code_to_enum() -> HashMap<String, Currency> {
    let mut map: HashMap<String, Currency> = HashMap::new();
    for item in ISO_CURRENCIES {
        let currency = get_currency_info(*item);
        map.insert(currency.iso_numeric_code.to_string(), *item);
    }
    map
}


// Macro that provides a constant to iterate over the Currency Enum.
macro_rules! define_enum {
    ($Name:ident { $($Variant:ident),* $(,)* }) => {
        /// Enumerates ISO-4217 Alphabetic Codes.
        #[derive(Debug, Copy, Clone, PartialEq, Serialize, Deserialize)]
        pub enum $Name {
            $($Variant),*,
        }
        // Array with all the valid currencies
        pub const ISO_CURRENCIES: &'static [$Name] = &[$($Name::$Variant),*];
    }
}

define_enum!(Currency {
    AED,
    AFN,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BYR,
    BZD,
    CAD,
    CDF,
    CHF,
    CLF,
    CLP,
    CNY,
    COP,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    IRR,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRU,
    MUR,
    MVR,
    MWK,
    MXN,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SKK,
    SLL,
    SOS,
    SRD,
    SSP,
    STD,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    UYU,
    UZS,
    VES,
    VND,
    VUV,
    WST,
    XAF,
    XAG,
    XAU,
    XBA,
    XBB,
    XBC,
    XBD,
    XCD,
    XDR,
    XOF,
    XPD,
    XPF,
    XPT,
    XTS,
    YER,
    ZAR,
    ZMK,
    ZMW,
    ZWL,
});


/// Returns a CurrencyInfo object given an ISO enum.
pub fn get_currency_info(code: Currency) -> CurrencyInfo {
    match code {
        Currency::AED => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "AED".to_string(),
            iso_numeric_code: "784".to_string(),
            minor_denomination: 25,
            name: "United Arab Emirates Dirham",
            symbol: "د.إ",
            symbol_first: false,
        },
        Currency::AFN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "AFN".to_string(),
            iso_numeric_code: "971".to_string(),
            minor_denomination: 100,
            name: "Afghan Afghani",
            symbol: "؋",
            symbol_first: false,
        },
        Currency::AMD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "AMD".to_string(),
            iso_numeric_code: "051".to_string(),
            minor_denomination: 10,
            name: "Armenian Dram",
            symbol: "դր.",
            symbol_first: false,
        },
        Currency::ANG => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "ANG".to_string(),
            iso_numeric_code: "532".to_string(),
            minor_denomination: 1,
            name: "Netherlands Antillean Gulden",
            symbol: "ƒ",
            symbol_first: false,
        },
        Currency::AOA => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "AOA".to_string(),
            iso_numeric_code: "973".to_string(),
            minor_denomination: 10,
            name: "Angolan Kwanza",
            symbol: "Kz",
            symbol_first: false,
        },
        Currency::ARS => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "ARS".to_string(),
            iso_numeric_code: "032".to_string(),
            minor_denomination: 1,
            name: "Argentine Peso",
            symbol: "$",
            symbol_first: true,
        },
        Currency::AUD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "AUD".to_string(),
            iso_numeric_code: "036".to_string(),
            minor_denomination: 5,
            name: "Australian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::AWG => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "AWG".to_string(),
            iso_numeric_code: "533".to_string(),
            minor_denomination: 5,
            name: "Aruban Florin",
            symbol: "ƒ",
            symbol_first: false,
        },
        Currency::AZN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "AZN".to_string(),
            iso_numeric_code: "944".to_string(),
            minor_denomination: 1,
            name: "Azerbaijani Manat",
            symbol: "₼",
            symbol_first: true,
        },
        Currency::BAM => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BAM".to_string(),
            iso_numeric_code: "977".to_string(),
            minor_denomination: 5,
            name: "Bosnia and Herzegovina Convertible Mark",
            symbol: "KM",
            symbol_first: true,
        },
        Currency::BBD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BBD".to_string(),
            iso_numeric_code: "052".to_string(),
            minor_denomination: 1,
            name: "Barbadian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::BDT => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BDT".to_string(),
            iso_numeric_code: "050".to_string(),
            minor_denomination: 1,
            name: "Bangladeshi Taka",
            symbol: "৳",
            symbol_first: true,
        },
        Currency::BGN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BGN".to_string(),
            iso_numeric_code: "975".to_string(),
            minor_denomination: 1,
            name: "Bulgarian Lev",
            symbol: "лв.",
            symbol_first: false,
        },
        Currency::BHD => CurrencyInfo {
            decimals: 3,
            iso_alpha_code: "BHD".to_string(),
            iso_numeric_code: "048".to_string(),
            minor_denomination: 5,
            name: "Bahraini Dinar",
            symbol: "ب.د",
            symbol_first: true,
        },
        Currency::BIF => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "BIF".to_string(),
            iso_numeric_code: "108".to_string(),
            minor_denomination: 100,
            name: "Burundian Franc",
            symbol: "Fr",
            symbol_first: false,
        },
        Currency::BMD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BMD".to_string(),
            iso_numeric_code: "060".to_string(),
            minor_denomination: 1,
            name: "Bermudian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::BND => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BND".to_string(),
            iso_numeric_code: "096".to_string(),
            minor_denomination: 1,
            name: "Brunei Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::BOB => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BOB".to_string(),
            iso_numeric_code: "068".to_string(),
            minor_denomination: 10,
            name: "Bolivian Boliviano",
            symbol: "Bs.",
            symbol_first: true,
        },
        Currency::BRL => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BRL".to_string(),
            iso_numeric_code: "986".to_string(),
            minor_denomination: 5,
            name: "Brazilian real",
            symbol: "R$",
            symbol_first: true,
        },
        Currency::BSD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BSD".to_string(),
            iso_numeric_code: "044".to_string(),
            minor_denomination: 1,
            name: "Bahamian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::BTN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BTN".to_string(),
            iso_numeric_code: "064".to_string(),
            minor_denomination: 5,
            name: "Bhutanese Ngultrum",
            symbol: "Nu.",
            symbol_first: false,
        },
        Currency::BWP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BWP".to_string(),
            iso_numeric_code: "072".to_string(),
            minor_denomination: 5,
            name: "Botswana Pula",
            symbol: "P",
            symbol_first: true,
        },
        Currency::BYN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BYN".to_string(),
            iso_numeric_code: "933".to_string(),
            minor_denomination: 1,
            name: "Belarusian Ruble",
            symbol: "Br",
            symbol_first: false,
        },
        Currency::BYR => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "BYR".to_string(),
            iso_numeric_code: "974".to_string(),
            minor_denomination: 100,
            name: "Belarusian Ruble",
            symbol: "Br",
            symbol_first: false,
        },
        Currency::BZD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "BZD".to_string(),
            iso_numeric_code: "084".to_string(),
            minor_denomination: 1,
            name: "Belize Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::CAD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "CAD".to_string(),
            iso_numeric_code: "124".to_string(),
            minor_denomination: 5,
            name: "Canadian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::CDF => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "CDF".to_string(),
            iso_numeric_code: "976".to_string(),
            minor_denomination: 1,
            name: "Congolese Franc",
            symbol: "Fr",
            symbol_first: false,
        },
        Currency::CHF => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "CHF".to_string(),
            iso_numeric_code: "756".to_string(),
            minor_denomination: 5,
            name: "Swiss Franc",
            symbol: "Fr",
            symbol_first: true,
        },
        Currency::CLF => CurrencyInfo {
            decimals: 4,
            iso_alpha_code: "CLF".to_string(),
            iso_numeric_code: "990".to_string(),
            minor_denomination: 5,
            name: "Unidad de Fomento",
            symbol: "UF",
            symbol_first: true,
        },
        Currency::CLP => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "CLP".to_string(),
            iso_numeric_code: "152".to_string(),
            minor_denomination: 1,
            name: "Chilean Peso",
            symbol: "$",
            symbol_first: true,
        },
        Currency::CNY => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "CNY".to_string(),
            iso_numeric_code: "156".to_string(),
            minor_denomination: 1,
            name: "Chinese Renminbi Yuan",
            symbol: "¥",
            symbol_first: true,
        },
        Currency::COP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "COP".to_string(),
            iso_numeric_code: "170".to_string(),
            minor_denomination: 20,
            name: "Colombian Peso",
            symbol: "$",
            symbol_first: true,
        },
        Currency::CRC => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "CRC".to_string(),
            iso_numeric_code: "188".to_string(),
            minor_denomination: 500, // TODO - Investigate
            name: "Costa Rican Colón",
            symbol: "₡",
            symbol_first: true,
        },
        Currency::CUC => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "CUC".to_string(),
            iso_numeric_code: "931".to_string(),
            minor_denomination: 1,
            name: "Cuban Convertible Peso",
            symbol: "$",
            symbol_first: false,
        },
        Currency::CUP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "CUP".to_string(),
            iso_numeric_code: "192".to_string(),
            minor_denomination: 1,
            name: "Cuban Peso",
            symbol: "$",
            symbol_first: true,
        },
        Currency::CVE => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "CVE".to_string(),
            iso_numeric_code: "132".to_string(),
            minor_denomination: 100,
            name: "Cape Verdean Escudo",
            symbol: "$",
            symbol_first: false,
        },
        Currency::CZK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "CZK".to_string(),
            iso_numeric_code: "203".to_string(),
            minor_denomination: 100,
            name: "Czech Koruna",
            symbol: "Kč",
            symbol_first: false,
        },
        Currency::DJF => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "DJF".to_string(),
            iso_numeric_code: "262".to_string(),
            minor_denomination: 100,
            name: "Djiboutian Franc",
            symbol: "Fdj",
            symbol_first: false,
        },
        Currency::DKK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "DKK".to_string(),
            iso_numeric_code: "208".to_string(),
            minor_denomination: 50,
            name: "Danish Krone",
            symbol: "kr.",
            symbol_first: false,
        },
        Currency::DOP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "DOP".to_string(),
            iso_numeric_code: "214".to_string(),
            minor_denomination: 100,
            name: "Dominican Peso",
            symbol: "$",
            symbol_first: true,
        },
        Currency::DZD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "DZD".to_string(),
            iso_numeric_code: "012".to_string(),
            minor_denomination: 100,
            name: "Algerian Dinar",
            symbol: "د.ج",
            symbol_first: false,
        },
        Currency::EGP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "EGP".to_string(),
            iso_numeric_code: "818".to_string(),
            minor_denomination: 25,
            name: "Egyptian Pound",
            symbol: "ج.م",
            symbol_first: true,
        },
        Currency::ERN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "ERN".to_string(),
            iso_numeric_code: "232".to_string(),
            minor_denomination: 1,
            name: "Eritrean Nakfa",
            symbol: "Nfk",
            symbol_first: false,
        },
        Currency::ETB => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "ETB".to_string(),
            iso_numeric_code: "230".to_string(),
            minor_denomination: 1,
            name: "Ethiopian Birr",
            symbol: "Br",
            symbol_first: false,
        },
        Currency::EUR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "EUR".to_string(),
            iso_numeric_code: "978".to_string(),
            minor_denomination: 1,
            name: "Euro",
            symbol: "€",
            symbol_first: true,
        },
        Currency::FJD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "FJD".to_string(),
            iso_numeric_code: "242".to_string(),
            minor_denomination: 5,
            name: "Fijian Dollar",
            symbol: "$",
            symbol_first: false,
        },
        Currency::FKP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "FKP".to_string(),
            iso_numeric_code: "238".to_string(),
            minor_denomination: 1,
            name: "Falkland Pound",
            symbol: "£",
            symbol_first: false,
        },
        Currency::GBP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "GBP".to_string(),
            iso_numeric_code: "826".to_string(),
            minor_denomination: 1,
            name: "British Pound",
            symbol: "£",
            symbol_first: true,
        },
        Currency::GEL => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "GEL".to_string(),
            iso_numeric_code: "981".to_string(),
            minor_denomination: 1,
            name: "Georgian Lari",
            symbol: "ლ",
            symbol_first: false,
        },
        Currency::GHS => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "GHS".to_string(),
            iso_numeric_code: "936".to_string(),
            minor_denomination: 1,
            name: "Ghanaian Cedi",
            symbol: "₵",
            symbol_first: true,
        },
        Currency::GIP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "GIP".to_string(),
            iso_numeric_code: "292".to_string(),
            minor_denomination: 1,
            name: "Gibraltar Pound",
            symbol: "£",
            symbol_first: true,
        },
        Currency::GMD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "GMD".to_string(),
            iso_numeric_code: "270".to_string(),
            minor_denomination: 1,
            name: "Gambian Dalasi",
            symbol: "D",
            symbol_first: false,
        },
        Currency::GNF => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "GNF".to_string(),
            iso_numeric_code: "324".to_string(),
            minor_denomination: 100,
            name: "Guinean Franc",
            symbol: "Fr",
            symbol_first: false,
        },
        Currency::GTQ => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "GTQ".to_string(),
            iso_numeric_code: "320".to_string(),
            minor_denomination: 1,
            name: "Guatemalan Quetzal",
            symbol: "Q",
            symbol_first: true,
        },
        Currency::GYD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "GYD".to_string(),
            iso_numeric_code: "328".to_string(),
            minor_denomination: 100,
            name: "Guyanese Dollar",
            symbol: "$",
            symbol_first: false,
        },
        Currency::HKD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "HKD".to_string(),
            iso_numeric_code: "344".to_string(),
            minor_denomination: 10,
            name: "Hong Kong Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::HNL => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "HNL".to_string(),
            iso_numeric_code: "340".to_string(),
            minor_denomination: 5,
            name: "Honduran Lempira",
            symbol: "L",
            symbol_first: true,
        },
        Currency::HRK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "HRK".to_string(),
            iso_numeric_code: "191".to_string(),
            minor_denomination: 1,
            name: "Croatian Kuna",
            symbol: "kn",
            symbol_first: false,
        },
        Currency::HTG => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "HTG".to_string(),
            iso_numeric_code: "332".to_string(),
            minor_denomination: 5,
            name: "Haitian Gourde",
            symbol: "G",
            symbol_first: false,
        },
        Currency::HUF => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "HUF".to_string(),
            iso_numeric_code: "348".to_string(),
            minor_denomination: 5,
            name: "Hungarian Forint",
            symbol: "Ft",
            symbol_first: false,
        },
        Currency::IDR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "IDR".to_string(),
            iso_numeric_code: "360".to_string(),
            minor_denomination: 5000,
            name: "Indonesian Rupiah",
            symbol: "Rp",
            symbol_first: true,
        },
        Currency::ILS => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "ILS".to_string(),
            iso_numeric_code: "376".to_string(),
            minor_denomination: 10,
            name: "Israeli New Sheqel",
            symbol: "₪",
            symbol_first: true,
        },
        Currency::INR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "INR".to_string(),
            iso_numeric_code: "356".to_string(),
            minor_denomination: 50,
            name: "Indian Rupee",
            symbol: "₹",
            symbol_first: true,
        },
        Currency::IQD => CurrencyInfo {
            decimals: 3,
            iso_alpha_code: "IQD".to_string(),
            iso_numeric_code: "368".to_string(),
            minor_denomination: 50000,
            name: "Iraqi Dinar",
            symbol: "ع.د",
            symbol_first: false,
        },
        Currency::IRR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "IRR".to_string(),
            iso_numeric_code: "364".to_string(),
            minor_denomination: 5000,
            name: "Iranian Rial",
            symbol: "﷼",
            symbol_first: true,
        },
        Currency::ISK => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "ISK".to_string(),
            iso_numeric_code: "352".to_string(),
            minor_denomination: 1,
            name: "Icelandic Króna",
            symbol: "kr",
            symbol_first: true,
        },
        Currency::JMD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "JMD".to_string(),
            iso_numeric_code: "388".to_string(),
            minor_denomination: 1,
            name: "Jamaican Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::JOD => CurrencyInfo {
            decimals: 3,
            iso_alpha_code: "JOD".to_string(),
            iso_numeric_code: "400".to_string(),
            minor_denomination: 5,
            name: "Jordanian Dinar",
            symbol: "د.ا",
            symbol_first: true,
        },
        Currency::JPY => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "JPY".to_string(),
            iso_numeric_code: "392".to_string(),
            minor_denomination: 1,
            name: "Japanese Yen",
            symbol: "¥",
            symbol_first: true,
        },
        Currency::KES => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "KES".to_string(),
            iso_numeric_code: "404".to_string(),
            minor_denomination: 50,
            name: "Kenyan Shilling",
            symbol: "KSh",
            symbol_first: true,
        },
        Currency::KGS => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "KGS".to_string(),
            iso_numeric_code: "417".to_string(),
            minor_denomination: 1,
            name: "Kyrgyzstani Som",
            symbol: "som",
            symbol_first: false,
        },
        Currency::KHR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "KHR".to_string(),
            iso_numeric_code: "116".to_string(),
            minor_denomination: 5000,
            name: "Cambodian Riel",
            symbol: "៛",
            symbol_first: false,
        },
        Currency::KMF => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "KMF".to_string(),
            iso_numeric_code: "174".to_string(),
            minor_denomination: 100,
            name: "Comorian Franc",
            symbol: "Fr",
            symbol_first: false,
        },
        Currency::KPW => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "KPW".to_string(),
            iso_numeric_code: "408".to_string(),
            minor_denomination: 1,
            name: "North Korean Won",
            symbol: "₩",
            symbol_first: false,
        },
        Currency::KRW => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "KRW".to_string(),
            iso_numeric_code: "410".to_string(),
            minor_denomination: 1,
            name: "South Korean Won",
            symbol: "₩",
            symbol_first: true,
        },
        Currency::KWD => CurrencyInfo {
            decimals: 3,
            iso_alpha_code: "KWD".to_string(),
            iso_numeric_code: "414".to_string(),
            minor_denomination: 5,
            name: "Kuwaiti Dinar",
            symbol: "د.ك",
            symbol_first: true,
        },
        Currency::KYD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "KYD".to_string(),
            iso_numeric_code: "136".to_string(),
            minor_denomination: 1,
            name: "Cayman Islands Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::KZT => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "KZT".to_string(),
            iso_numeric_code: "398".to_string(),
            minor_denomination: 100,
            name: "Kazakhstani Tenge",
            symbol: "₸",
            symbol_first: false,
        },
        Currency::LAK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "LAK".to_string(),
            iso_numeric_code: "418".to_string(),
            minor_denomination: 10,
            name: "Lao Kip",
            symbol: "₭",
            symbol_first: false,
        },
        Currency::LBP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "LBP".to_string(),
            iso_numeric_code: "422".to_string(),
            minor_denomination: 25000,
            name: "Lebanese Pound",
            symbol: "ل.ل",
            symbol_first: true,
        },
        Currency::LKR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "LKR".to_string(),
            iso_numeric_code: "144".to_string(),
            minor_denomination: 100,
            name: "Sri Lankan Rupee",
            symbol: "₨",
            symbol_first: false,
        },
        Currency::LRD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "LRD".to_string(),
            iso_numeric_code: "430".to_string(),
            minor_denomination: 5,
            name: "Liberian Dollar",
            symbol: "$",
            symbol_first: false,
        },
        Currency::LSL => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "LSL".to_string(),
            iso_numeric_code: "426".to_string(),
            minor_denomination: 1,
            name: "Lesotho Loti",
            symbol: "L",
            symbol_first: false,
        },
        Currency::LYD => CurrencyInfo {
            decimals: 3,
            iso_alpha_code: "LYD".to_string(),
            iso_numeric_code: "434".to_string(),
            minor_denomination: 50,
            name: "Libyan Dinar",
            symbol: "ل.د",
            symbol_first: false,
        },
        Currency::MAD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MAD".to_string(),
            iso_numeric_code: "504".to_string(),
            minor_denomination: 1,
            name: "Moroccan Dirham",
            symbol: "د.م.",
            symbol_first: false,
        },
        Currency::MDL => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MDL".to_string(),
            iso_numeric_code: "498".to_string(),
            minor_denomination: 1,
            name: "Moldovan Leu",
            symbol: "L",
            symbol_first: false,
        },
        Currency::MGA => CurrencyInfo {
            decimals: 1, // TODO - decimals is 1/5th need to represent somehow
            iso_alpha_code: "MGA".to_string(),
            iso_numeric_code: "969".to_string(),
            minor_denomination: 1,
            name: "Malagasy Ariary",
            symbol: "Ar",
            symbol_first: true,
        },
        Currency::MKD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MKD".to_string(),
            iso_numeric_code: "807".to_string(),
            minor_denomination: 100,
            name: "Macedonian Denar",
            symbol: "ден",
            symbol_first: false,
        },
        Currency::MMK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MMK".to_string(),
            iso_numeric_code: "104".to_string(),
            minor_denomination: 50,
            name: "Myanmar Kyat",
            symbol: "K",
            symbol_first: false,
        },
        Currency::MNT => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MNT".to_string(),
            iso_numeric_code: "496".to_string(),
            minor_denomination: 2000,
            name: "Mongolian Tögrög",
            symbol: "₮",
            symbol_first: false,
        },
        Currency::MOP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MOP".to_string(),
            iso_numeric_code: "446".to_string(),
            minor_denomination: 10,
            name: "Macanese Pataca",
            symbol: "P",
            symbol_first: false,
        },
        Currency::MRU => CurrencyInfo {
            decimals: 1, // TODO - decimals problem of 5
            iso_alpha_code: "MRU".to_string(),
            iso_numeric_code: "929".to_string(),
            minor_denomination: 1,
            name: "Mauritanian Ouguiya",
            symbol: "UM",
            symbol_first: false,
        },
        Currency::MUR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MUR".to_string(),
            iso_numeric_code: "480".to_string(),
            minor_denomination: 100,
            name: "Mauritian Rupee",
            symbol: "₨",
            symbol_first: true,
        },
        Currency::MVR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MVR".to_string(),
            iso_numeric_code: "462".to_string(),
            minor_denomination: 100,
            name: "Maldivian Rufiyaa",
            symbol: "MVR",
            symbol_first: false,
        },
        Currency::MWK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MWK".to_string(),
            iso_numeric_code: "454".to_string(),
            minor_denomination: 1,
            name: "Malawian Kwacha",
            symbol: "MK",
            symbol_first: false,
        },
        Currency::MXN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MXN".to_string(),
            iso_numeric_code: "484".to_string(),
            minor_denomination: 5,
            name: "Mexican Peso",
            symbol: "$",
            symbol_first: true,
        },
        Currency::MYR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MYR".to_string(),
            iso_numeric_code: "458".to_string(),
            minor_denomination: 5,
            name: "Malaysian Ringgit",
            symbol: "RM",
            symbol_first: true,
        },
        Currency::MZN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "MZN".to_string(),
            iso_numeric_code: "943".to_string(),
            minor_denomination: 1,
            name: "Mozambican Metical",
            symbol: "MTn",
            symbol_first: true,
        },
        Currency::NAD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "NAD".to_string(),
            iso_numeric_code: "516".to_string(),
            minor_denomination: 5,
            name: "Namibian Dollar",
            symbol: "$",
            symbol_first: false,
        },
        Currency::NGN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "NGN".to_string(),
            iso_numeric_code: "566".to_string(),
            minor_denomination: 50,
            name: "Nigerian Naira",
            symbol: "₦",
            symbol_first: true,
        },
        Currency::NIO => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "NIO".to_string(),
            iso_numeric_code: "588".to_string(),
            minor_denomination: 5,
            name: "Nicaraguan Córdoba",
            symbol: "C$",
            symbol_first: true,
        },
        Currency::NOK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "NOK".to_string(),
            iso_numeric_code: "578".to_string(),
            minor_denomination: 100,
            name: "Norwegian Krone",
            symbol: "kr",
            symbol_first: false,
        },
        Currency::NPR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "NPR".to_string(),
            iso_numeric_code: "524".to_string(),
            minor_denomination: 1,
            name: "Nepalese Rupee",
            symbol: "₨",
            symbol_first: true,
        },
        Currency::NZD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "NZD".to_string(),
            iso_numeric_code: "554".to_string(),
            minor_denomination: 10,
            name: "New Zealand Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::OMR => CurrencyInfo {
            decimals: 3,
            iso_alpha_code: "OMR".to_string(),
            iso_numeric_code: "512".to_string(),
            minor_denomination: 5,
            name: "Omani Rial",
            symbol: "ر.ع.",
            symbol_first: true,
        },
        Currency::PAB => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "PAB".to_string(),
            iso_numeric_code: "590".to_string(),
            minor_denomination: 1,
            name: "Panamanian Balboa",
            symbol: "B/.",
            symbol_first: true,
        },
        Currency::PEN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "PEN".to_string(),
            iso_numeric_code: "604".to_string(),
            minor_denomination: 1,
            name: "Peruvian Sol",
            symbol: "S/",
            symbol_first: true,
        },
        Currency::PGK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "PGK".to_string(),
            iso_numeric_code: "598".to_string(),
            minor_denomination: 5,
            name: "Papua New Guinean Kina",
            symbol: "K",
            symbol_first: false,
        },
        Currency::PHP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "PHP".to_string(),
            iso_numeric_code: "608".to_string(),
            minor_denomination: 1,
            name: "Philippine Peso",
            symbol: "₱",
            symbol_first: true,
        },
        Currency::PKR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "PKR".to_string(),
            iso_numeric_code: "586".to_string(),
            minor_denomination: 100,
            name: "Pakistani Rupee",
            symbol: "₨",
            symbol_first: true,
        },
        Currency::PLN => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "PLN".to_string(),
            iso_numeric_code: "985".to_string(),
            minor_denomination: 1,
            name: "Polish Złoty",
            symbol: "zł",
            symbol_first: false,
        },
        Currency::PYG => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "PYG".to_string(),
            iso_numeric_code: "600".to_string(),
            minor_denomination: 5000,
            name: "Paraguayan Guaraní",
            symbol: "₲",
            symbol_first: true,
        },
        Currency::QAR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "QAR".to_string(),
            iso_numeric_code: "634".to_string(),
            minor_denomination: 1,
            name: "Qatari Riyal",
            symbol: "ر.ق",
            symbol_first: false,
        },
        Currency::RON => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "RON".to_string(),
            iso_numeric_code: "946".to_string(),
            minor_denomination: 1,
            name: "Romanian Leu",
            symbol: "ر.ق",
            symbol_first: false,
        },
        Currency::RSD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "RSD".to_string(),
            iso_numeric_code: "941".to_string(),
            minor_denomination: 100,
            name: "Serbian Dinar",
            symbol: "РСД",
            symbol_first: true,
        },
        Currency::RUB => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "RUB".to_string(),
            iso_numeric_code: "643".to_string(),
            minor_denomination: 1,
            name: "Russian Ruble",
            symbol: "₽",
            symbol_first: false,
        },
        Currency::RWF => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "RWF".to_string(),
            iso_numeric_code: "646".to_string(),
            minor_denomination: 100,
            name: "Rwandan Franc",
            symbol: "FRw",
            symbol_first: false,
        },
        Currency::SAR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SAR".to_string(),
            iso_numeric_code: "682".to_string(),
            minor_denomination: 5,
            name: "Saudi Riyal",
            symbol: "ر.س",
            symbol_first: true,
        },
        Currency::SBD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SBD".to_string(),
            iso_numeric_code: "090".to_string(),
            minor_denomination: 10,
            name: "Solomon Islands Dollar",
            symbol: "$",
            symbol_first: false,
        },
        Currency::SCR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SCR".to_string(),
            iso_numeric_code: "690".to_string(),
            minor_denomination: 1,
            name: "Seychellois Rupee",
            symbol: "₨",
            symbol_first: false,
        },
        Currency::SDG => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SDG".to_string(),
            iso_numeric_code: "938".to_string(),
            minor_denomination: 1,
            name: "Sudanese Pound",
            symbol: "£",
            symbol_first: true,
        },
        Currency::SEK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SEK".to_string(),
            iso_numeric_code: "752".to_string(),
            minor_denomination: 100,
            name: "Swedish Krona",
            symbol: "kr",
            symbol_first: false,
        },
        Currency::SGD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SGD".to_string(),
            iso_numeric_code: "702".to_string(),
            minor_denomination: 1,
            name: "Singapore Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::SHP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SHP".to_string(),
            iso_numeric_code: "654".to_string(),
            minor_denomination: 1,
            name: "Saint Helenian Pound",
            symbol: "£",
            symbol_first: false,
        },
        Currency::SKK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SKK".to_string(),
            iso_numeric_code: "703".to_string(),
            minor_denomination: 50,
            name: "Slovak Koruna",
            symbol: "Sk",
            symbol_first: true,
        },
        Currency::SLL => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SLL".to_string(),
            iso_numeric_code: "694".to_string(),
            minor_denomination: 1000,
            name: "Sierra Leonean Leone",
            symbol: "Le",
            symbol_first: false,
        },
        Currency::SOS => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SOS".to_string(),
            iso_numeric_code: "706".to_string(),
            minor_denomination: 1,
            name: "Somali Shilling",
            symbol: "Sh",
            symbol_first: false,
        },
        Currency::SRD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SRD".to_string(),
            iso_numeric_code: "968".to_string(),
            minor_denomination: 1,
            name: "Surinamese Dollar",
            symbol: "$",
            symbol_first: false,
        },
        Currency::SSP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SSP".to_string(),
            iso_numeric_code: "728".to_string(),
            minor_denomination: 5,
            name: "South Sudanese Pound",
            symbol: "£",
            symbol_first: false,
        },
        Currency::STD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "STD".to_string(),
            iso_numeric_code: "678".to_string(),
            minor_denomination: 10000,
            name: "São Tomé and Príncipe Dobra",
            symbol: "Db",
            symbol_first: false,
        },
        Currency::SVC => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SVC".to_string(),
            iso_numeric_code: "222".to_string(),
            minor_denomination: 1,
            name: "Salvadoran Colón",
            symbol: "₡",
            symbol_first: true,
        },
        Currency::SYP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SYP".to_string(),
            iso_numeric_code: "760".to_string(),
            minor_denomination: 100,
            name: "Syrian Pound",
            symbol: "£S",
            symbol_first: false,
        },
        Currency::SZL => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "SZL".to_string(),
            iso_numeric_code: "748".to_string(),
            minor_denomination: 1,
            name: "Swazi Lilangeni",
            symbol: "E",
            symbol_first: true,
        },
        Currency::THB => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "THB".to_string(),
            iso_numeric_code: "764".to_string(),
            minor_denomination: 1,
            name: "Thai Baht",
            symbol: "฿",
            symbol_first: true,
        },
        Currency::TJS => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "TJS".to_string(),
            iso_numeric_code: "972".to_string(),
            minor_denomination: 1,
            name: "Tajikistani Somoni",
            symbol: "ЅМ",
            symbol_first: false,
        },
        Currency::TMT => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "TMT".to_string(),
            iso_numeric_code: "934".to_string(),
            minor_denomination: 1,
            name: "Turkmenistani Manat",
            symbol: "T",
            symbol_first: false,
        },
        Currency::TND => CurrencyInfo {
            decimals: 3,
            iso_alpha_code: "TND".to_string(),
            iso_numeric_code: "788".to_string(),
            minor_denomination: 10,
            name: "Tunisian Dinar",
            symbol: "د.ت",
            symbol_first: false,
        },
        Currency::TOP => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "TOP".to_string(),
            iso_numeric_code: "776".to_string(),
            minor_denomination: 1,
            name: "Tongan Paʻanga",
            symbol: "T$",
            symbol_first: true,
        },
        Currency::TRY => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "TRY".to_string(),
            iso_numeric_code: "949".to_string(),
            minor_denomination: 1,
            name: "Turkish Lira",
            symbol: "₺",
            symbol_first: true,
        },
        Currency::TTD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "TTD".to_string(),
            iso_numeric_code: "780".to_string(),
            minor_denomination: 1,
            name: "Trinidad and Tobago Dollar",
            symbol: "$",
            symbol_first: false,
        },
        Currency::TWD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "TWD".to_string(),
            iso_numeric_code: "901".to_string(),
            minor_denomination: 50,
            name: "New Taiwan Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::TZS => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "TZS".to_string(),
            iso_numeric_code: "834".to_string(),
            minor_denomination: 5000,
            name: "Tanzanian Shilling",
            symbol: "Sh",
            symbol_first: true,
        },
        Currency::UAH => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "UAH".to_string(),
            iso_numeric_code: "980".to_string(),
            minor_denomination: 1,
            name: "Ukrainian Hryvnia",
            symbol: "₴",
            symbol_first: false,
        },
        Currency::UGX => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "UGX".to_string(),
            iso_numeric_code: "800".to_string(),
            minor_denomination: 1000,
            name: "Ugandan Shilling",
            symbol: "USh",
            symbol_first: false,
        },
        Currency::USD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "USD".to_string(),
            iso_numeric_code: "840".to_string(),
            minor_denomination: 1,
            name: "United States Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::UYU => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "UYU".to_string(),
            iso_numeric_code: "858".to_string(),
            minor_denomination: 100,
            name: "Uruguayan Peso",
            symbol: "$",
            symbol_first: true,
        },
        Currency::UZS => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "UZS".to_string(),
            iso_numeric_code: "860".to_string(),
            minor_denomination: 100,
            name: "Uzbekistan Som",
            symbol: "so'm",
            symbol_first: false,
        },
        Currency::VES => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "VES".to_string(),
            iso_numeric_code: "928".to_string(),
            minor_denomination: 1,
            name: "Venezuelan Bolívar Soberano",
            symbol: "Bs",
            symbol_first: true,
        },
        Currency::VND => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "VND".to_string(),
            iso_numeric_code: "704".to_string(),
            minor_denomination: 100,
            name: "Vietnamese Đồng",
            symbol: "₫",
            symbol_first: false,
        },
        Currency::VUV => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "VUV".to_string(),
            iso_numeric_code: "548".to_string(),
            minor_denomination: 1,
            name: "Vanuatu Vatu",
            symbol: "Vt",
            symbol_first: true,
        },
        Currency::WST => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "WST".to_string(),
            iso_numeric_code: "882".to_string(),
            minor_denomination: 10,
            name: "Samoan Tala",
            symbol: "T",
            symbol_first: false,
        },
        Currency::XAF => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XAF".to_string(),
            iso_numeric_code: "950".to_string(),
            minor_denomination: 100,
            name: "Central African Cfa Franc",
            symbol: "CFA",
            symbol_first: false,
        },
        Currency::XAG => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XAG".to_string(),
            iso_numeric_code: "961".to_string(),
            minor_denomination: 100,
            name: "Silver (Troy Ounce)",
            symbol: "oz t",
            symbol_first: false,
        },
        Currency::XAU => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XAU".to_string(),
            iso_numeric_code: "959".to_string(),
            minor_denomination: 100,
            name: "Gold (Troy Ounce)",
            symbol: "oz t",
            symbol_first: false,
        },
        Currency::XBA => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XBA".to_string(),
            iso_numeric_code: "955".to_string(),
            minor_denomination: 100,
            name: "European Composite Unit",
            symbol: "",
            symbol_first: false,
        },
        Currency::XBB => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XBB".to_string(),
            iso_numeric_code: "956".to_string(),
            minor_denomination: 100,
            name: "European Monetary Unit",
            symbol: "",
            symbol_first: false,
        },
        Currency::XBC => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XBC".to_string(),
            iso_numeric_code: "957".to_string(),
            minor_denomination: 100,
            name: "European Unit of Account 9",
            symbol: "",
            symbol_first: false,
        },
        Currency::XBD => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XBD".to_string(),
            iso_numeric_code: "958".to_string(),
            minor_denomination: 100,
            name: "European Unit of Account 17",
            symbol: "",
            symbol_first: false,
        },
        Currency::XCD => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "XCD".to_string(),
            iso_numeric_code: "951".to_string(),
            minor_denomination: 1,
            name: "East Caribbean Dollar",
            symbol: "$",
            symbol_first: true,
        },
        Currency::XDR => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XDR".to_string(),
            iso_numeric_code: "960".to_string(),
            minor_denomination: 100,
            name: "Special Drawing Rights",
            symbol: "SDR",
            symbol_first: false,
        },
        Currency::XOF => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XOF".to_string(),
            iso_numeric_code: "952".to_string(),
            minor_denomination: 100,
            name: "West African Cfa Franc",
            symbol: "Fr",
            symbol_first: false,
        },
        Currency::XPD => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XPD".to_string(),
            iso_numeric_code: "964".to_string(),
            minor_denomination: 100,
            name: "Palladium",
            symbol: "oz t",
            symbol_first: false,
        },
        Currency::XPF => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XPF".to_string(),
            iso_numeric_code: "953".to_string(),
            minor_denomination: 100,
            name: "Cfp Franc",
            symbol: "Fr",
            symbol_first: false,
        },
        Currency::XPT => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XPT".to_string(),
            iso_numeric_code: "962".to_string(),
            minor_denomination: 100,
            name: "Platinum",
            symbol: "oz t",
            symbol_first: false,
        },
        Currency::XTS => CurrencyInfo {
            decimals: 0,
            iso_alpha_code: "XTS".to_string(),
            iso_numeric_code: "963".to_string(),
            minor_denomination: 100,
            name: "Codes specifically reserved for testing purposes",
            symbol: "oz t",
            symbol_first: false,
        },
        Currency::YER => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "YER".to_string(),
            iso_numeric_code: "886".to_string(),
            minor_denomination: 100,
            name: "Yemeni Rial",
            symbol: "﷼",
            symbol_first: false,
        },
        Currency::ZAR => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "ZAR".to_string(),
            iso_numeric_code: "710".to_string(),
            minor_denomination: 10,
            name: "South African Rand",
            symbol: "R",
            symbol_first: true,
        },
        Currency::ZMK => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "ZMK".to_string(),
            iso_numeric_code: "894".to_string(),
            minor_denomination: 5,
            name: "Zambian Kwacha",
            symbol: "ZK",
            symbol_first: false,
        },
        Currency::ZMW => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "ZMW".to_string(),
            iso_numeric_code: "967".to_string(),
            minor_denomination: 5,
            name: "Zambian Kwacha",
            symbol: "K",
            symbol_first: true,
        },
        Currency::ZWL => CurrencyInfo {
            decimals: 2,
            iso_alpha_code: "ZWL".to_string(),
            iso_numeric_code: "932".to_string(),
            minor_denomination: 1,
            name: "Zimbabwe Dollar",
            symbol: "Z$",
            symbol_first: true,
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn iso_enum_name_matches_currency_iso_alpha_code() {
        for iso in ISO_CURRENCIES {
            let iso_alpha_code = format!("{}", *iso);
            let currency = get_currency_info(iso);
            assert_eq!(iso_alpha_code, currency.iso_alpha_code);
        }
    }

    #[test]
    fn no_duplicate_currency_numeric_iso_codes() {
        let mut numeric_codes: Vec<_> = ISO_CURRENCIES
            .iter()
            .map(|iso| get_currency_info(*iso).iso_numeric_code)
            .collect();

        numeric_codes.sort();
        numeric_codes.dedup();
        assert_eq!(ISO_CURRENCIES.len(), numeric_codes.len());
    }
}
